### ISSUE TITLE
Quality Assessment Checklist

### ISSUE THREAD

**Issue by maxhelgestad** [CS317-Team2/Team2-Issues#3]
**Team Culture:**
- [x] Build team culture through non-work activities.
          Played Among Us as a group
- [X] Regularly recognize and complement team members for their contributions.
         During zoom meetings, with each other thanked and expressed appreciation for things done on projects.
- [X] Respectfully provide coaching to improve team effectiveness and efficiency.

**Communication:**
- [X] Set up and use communication tools and processes for effective and rapid information exchange. [Slack](https://app.slack.com/client/T01BSH0BNRX/C01BL44DQ6Q) [GitHub](https://github.com/CS317-Team2/) 
- [X] Use these tools and processes regularly.
- [X] Establish and use remote communication tools and processes for distributed team interactions.
- [x] Establish and use initiation and exit checklists. [Link](https://github.com/CS317-Team2/Team2-Issues/issues/1)
- [X] Establish and use team policy statement. [Link](https://github.com/CS317-Team2/Team2-Issues/issues/2)

**Testing:**
- [X] Design and execute tests for confirming refined user stories match initial user stories. [CardDeckTest](https://github.com/CS317-Team2/SolitaireSimulation/blob/main/CardDeckTest.java)
- [ ] Design and execute tests for confirming design matches refined user stories.
- [ ] Design and execute tests for confirming implementation matches design.
- [X] Create basic execution test capabilities. [CardDeckTest](https://github.com/CS317-Team2/JavaSolitaireSimulation/blob/master/test/CardDeckTest.java)
- [ ] Create comprehensive test capabilities.
- [X] Create and regularly use unit testing. [Link](https://github.com/CS317-Team2/JavaSolitaireSimulation/blob/master/test/CardDeckTest.java)
- [ ] Use a pull-request, code-review integration process for source changes.
- [ ] Automatically monitor and report code coverage.
- [X] Use test-driven development. [RateTesting](https://github.com/CS317-Team2/MarchMadness/blob/master/src/RatingTest.java), [RateTesting2](https://github.com/CS317-Team2/MarchMadness/blob/master/src/RatingTest2.java) and [FileTester](https://github.com/CS317-Team2/MarchMadness/blob/master/src/FileTester.java)
- [ ] Measure and track software performance.

**Requirements and Analysis:**
- [X] Create user stories to capture basic product requirements. [User_Stories](https://docs.google.com/document/d/1nMKvf5gvPgRilLPFhHx_E-oUKQNjGVcG3bm4PbH23F4/edit)
- [X] Analyze, refine, prioritize, select and convert user stories into tasks for development. 
- [ ] Organize tasks into Epic-story-task packages.
- [ ] Experiment with Job Stories as an alternative to User Stories (see https://maherou.github.io/files/CS317/CS317-Links).

**Design:**
- [X] Create basic design documents such as class, interaction and use case. [Design_Doc](https://docs.google.com/document/d/1nOtG3kkf8UyMPY1GWDWf6OQunuX-lAANUxaSPDtCyf0/edit)
- [X] Write lightweight design documents [Link](https://docs.google.com/document/d/1nOtG3kkf8UyMPY1GWDWf6OQunuX-lAANUxaSPDtCyf0/edit)
- [x] Write throw-away prototype code to explore high-risk design elements. [RateTesting](https://github.com/CS317-Team2/MarchMadness/blob/master/src/RatingTest.java), [RateTesting2](https://github.com/CS317-Team2/MarchMadness/blob/master/src/RatingTest2.java) and [FileTester](https://github.com/CS317-Team2/MarchMadness/blob/master/src/FileTester.java). MVP: [RankingDriver](https://github.com/CS317-Team2/MarchMadness/blob/master/src/RankingDriver.java)

**Development:**
- [X] Create GitHub Isses describing major design and development tasks. [Link](https://github.com/CS317-Team2/Team2-Issues)
- [X] Establish GitHub Project (Kanban) board. [Solitaire](https://github.com/orgs/CS317-Team2/projects/1) [MarchMadness](https://github.com/CS317-Team2/MarchMadness/projects/1)
- [x] Actively manage work by tracking issues on your Kanban board.
- [x] Conduct regular project meetings to assess progress and manage schedule.
- [ ] Use code formatting tool to assure uniform source code.
- [ ] Identify and use a coding convention.
- [x] Develop in-source comments that can be used to generate documentation, e.g., Javadoc or Doxygen. [Solitaire_Doc](https://github.com/CS317-Team2/JavaSolitaireSimulation/tree/master/doc) and [MarchMadness_Doc](https://github.com/CS317-Team2/MarchMadness/tree/master/doc)

**Product Release:**
- [ ] Create a unique and traceable release of your software product.
- [ ] Make a citable version (with DOI) of your code and make it available on Zenodo or Figshare.
- [x] Generate user and developer documentation. [Solitaire_Doc](https://github.com/CS317-Team2/JavaSolitaireSimulation/tree/master/doc) and [MarchMadness_Doc](https://github.com/CS317-Team2/MarchMadness/tree/master/doc)
- [ ] Create product branding, e.g. logo family, catchphrase, product description.
